# Site Settings
title: Aditya's Portfolio
description: A showcase of my projects, skills, and contributions.
baseurl: ""  # Leave empty if hosting on lelepentol.github.io
url: "https://lelepentol.github.io"  # Your GitHub Pages URL
github_username: lelepentol
email: your-email@example.com  # Optional (add if you want contact)

# Jekyll Settings
theme: jekyll-theme-modern-resume  # If using the Modern Resume Theme
plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata

# Social Media Links (customize with your profiles)
social:
  - name: GitHub
    icon: github
    url: https://github.com/lelepentol

# Navigation Links
navbar:
  - name: Home
    url: /
  - name: Projects
    url: /#projects
  - name: About
    url: /#about

# About Section
about:
  name: Aditya Novian
  role: Open-Source & Automation Enthusiast
  summary: |
    Passionate about coding, automation, and sharing knowledge. 
    Love building tools that solve real-world problems.
  image: /assets/images/avatar.jpg  # Upload your photo to `assets/images/`

# Skills Section (customize with your tech stack)
skills:
  - name: JavaScript
    level: 70
  - name: Git/GitHub
    level: 80
  - name: HTML/CSS
    level: 75
  - name: Bash
    level: 75

# Projects Section (link your GitHub repos)
projects:
  - title: HR Question Generator with AI
    description: Project lets you upload a candidate's CV (PDF), extract it as Markdown, and use a local LLM (Gemma via Ollama) to generate simple HR interview questions with probable answers.
    github_url: https://github.com/lelepentol/HRQuestionGeneratorWithAI
    tags: [JavaScript, Automation, LLM, AI]
  - title: Repository 2
    description: Automation using Ruby as the framework
    github_url: https://github.com/lelepentol/ruby-automation
    tags: [Ruby, Automation]